### ISSUE TITLE
usermode

### ISSUE THREAD

**Issue by Glowman554** [V01D-NULL/MoonOS#1]
Hi i saw that your are looking for help with getting ValidityOS into usermode. Maybe this helps http://www.jamesmolloy.co.uk/tutorial_html/10.-User%20Mode.html.

Have a nice day.

**Comment by V01D-NULL** [comment]
I think I have tried this but I got some errors or something I dont remember. 

I will take a look at it, thank you 🙏
(Ps feel free to communicate in german if it is easier for you)

**Comment by Glowman554** [comment]
Oh auch ein deutscher cool

**Comment by V01D-NULL** [comment]
👍😉

**Comment by Glowman554** [comment]
Das mit dem usermode kanst du gleichzeitig mit dem multitasking beheben. In dem tutorial (http://www.lowlevel.eu/wiki/Teil_6_-_Multitasking) wird ab hier erklärt wie man das umsetzen kann. Es geht bis zu teil 8 wo man dan im usermode ist und sein erstes externes programm am laufen hatt.

**Comment by V01D-NULL** [comment]
Ah krass vielen Dank!

**Comment by Glowman554** [comment]
Kein problem.

**Comment by Glowman554** [comment]
Wen du wilst kanst du auf meinen discord server joinen (https://discord.gg/qfYBHFWDcK) da kann ich dan fragen und so leichter beantwirten.
