### ISSUE TITLE
Cannot build on wsl2 on Windows 11

### ISSUE THREAD

**Issue by miiguemm01** [V01D-NULL/MoonOS#3]
Make cannot find target/makefile
"Error 2" on line 33.

![imagen](https://user-images.githubusercontent.com/75725554/139052715-2b49e8af-b127-4653-b4e1-677f8c6fca50.png)

**Comment by V01D-NULL** [comment]
Hi, thanks for checking out my kernel :)
Sorry for the late reply, didn't see an issue being opened
It sounds like you didn't clone the submodules which are `echfs` and `limine`
Please try running `git submodule init && git submodule update`
